# -*- coding: utf-8 -*-
"""Scrapping

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LA90RWE8Ut6HvTKrBH3TQabSKZge4Yn9
"""

import requests
from bs4 import BeautifulSoup
from tqdm import tqdm
import pandas as pd

"""Membuat Koneksi pada Website yang akan discraping"""

# set Url
URL = "https://quotes.toscrape.com/"

# get connection
resp = requests.get(URL)

# check status code
resp.status_code

"""Mengubah isi website menjadi text"""

# mengubah response website dalam bentuk text
resp.text

"""Mengubah isi website menjadi HTML base"""

# establish connection
resp = requests.get(URL)

# membuat object untuk scraping
soup = BeautifulSoup(resp.text, "html.parser")

soup

"""Mengekstrak data Quotes, Author dan Tag, dari semua halaman"""

# list untuk menyimpan semua data hasil ekstraksi
full_data = []

for page in tqdm(range(1, 11)):
  resp = requests.get(f'https://quotes.toscrape.com/page/{page}')

  soup = BeautifulSoup(resp.text, 'html.parser')

  # get all data based on html tags
  raw_data = soup.find_all('div', class_='quote')

  # perulangan untuk mengambil data yg dibutuhkan
  for data in raw_data:
    # only extract the text
    quotes = data.find("span").text

    # extract author
    author = data.find('small').text

    # get tags
    tags = data.find_all('a', class_='tag')

    # create empty list for store all tag value
    get_tag = []

    for tag in tags:
      get_tag.append(tag.text)

    data = {
        'quote':quotes,
        'author':author,
        'tag':get_tag
    }

    full_data.append(data)

  full_data

"""Mengubah data yang sudah discraping menjadi DataFrame"""

quote_data = pd.DataFrame(full_data)

quote_data

"""Menyimpan data menjadi csv"""

# export to csv
quote_data.to_csv('quotes_scrape_data.csv', index = False)

# validate if the result is the same
pd.read_csv('quotes_scrape_data.csv')

"""Menyimpan data pada Database"""

# Membuat schema pada database

'''sql
	CREATE TABLE public.quotes_data (
		"quote" varchar NULL,
		author varchar NULL,
		tags varchar NULL
	);
	'''

from sqlalchemy import create_engine

"""Membuat koneksi pada database"""

# create connection
conn = create_engine("postgresql://postgres:cobapassword@localhost/data-wrangling")

"""Memasukan data ke database menggunakan pandas"""

# insert data to database using pandas
quote_data.to_sql(name = "quotes_data", con = conn,
                  if_exists = "append", index = False)

"""Memeriksa apakah data sudah berhasil masuk database"""

query = "SELECT * FROM quotes_data"

pd.read_sql(sql = query, con= conn)

"""Scraping data menggunakan API website"""

resp = requests.get("https://recommendation.kgdata.dev/chrono/v1/wp_aio?t=1790210545496")

resp.status_code

"""Mengubah menjadi json"""

# Convert API menjadi Json
raw_respon = resp.json()

raw_respon

"""Mengambil key yang akan diambil"""

# Membuat dataframe dari Json
quote_data_json = pd.DataFrame(raw_respon['data']['top_overview'])

quote_data_json